Web/PruebaTec.Gbso.Web/Models/ErrorViewModel.cs
using System;

namespace PruebaTec.Gbso.Web.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Web/PruebaTec.Gbso.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PruebaTec.Gbso.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTec.Gbso.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Web/PruebaTec.Gbso.Web/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PruebaTec.Gbso.Web.Models;
using PruebaTec.Gbso.Web.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTec.Gbso.Web.Controllers
{
	public class UsuarioController : Controller
	{
		private readonly IUsuarioService UsuarioService;

		public UsuarioController(IUsuarioService usuarioService)
		{
			this.UsuarioService = usuarioService;
		}

		public ActionResult Usuarios()
		{
			return View();
		}

		public async Task<ActionResult> Usuario(int id)
		{
			var usuario = await UsuarioService.ConsultarAsync(id);
			return View(usuario);
		}

		public async Task<ActionResult> Crear(UsuarioModel usuarioModel)
		{
			await UsuarioService.RegistrarAsync(usuarioModel);
			return View();
		}

		public async Task<ActionResult> Editar(int id)
		{
			return await Usuario(id);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public Task<ActionResult> Editar(int id, IFormCollection collection)
		{
			throw new NotImplementedException();
		}

		public Task<ActionResult> Eliminar(int id)
		{
			throw new NotImplementedException();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public Task<ActionResult> Eliminar(int id, IFormCollection collection)
		{
			throw new NotImplementedException();
		}
	}
}

Web/PruebaTec.Gbso.Web/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PruebaTec.Gbso.Web.Models;
using PruebaTec.Gbso.Web.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTec.Gbso.Web.Controllers
{
	public class UsuariosController : Controller
	{
		private readonly IUsuarioService UsuarioService;

		public UsuariosController(IUsuarioService usuarioService)
		{
			this.UsuarioService = usuarioService;
		}

		public async Task<ActionResult> Index()
		{
			var usuarios = await UsuarioService.ConsultarAsync();
			return View(usuarios);
		}

		public async Task<PartialViewResult> Usuario(int id)
		{
			var usuario = await UsuarioService.ConsultarAsync(id);
			return PartialView(usuario);
		}

		public async Task<PartialViewResult> Crear(UsuarioModel usuarioModel)
		{
			await UsuarioService.RegistrarAsync(usuarioModel);
			return PartialView();
		}

		public async Task<PartialViewResult> Editar(int id)
		{
			return await Usuario(id);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public Task<PartialViewResult> Editar(int id, IFormCollection collection)
		{
			throw new NotImplementedException();
		}

		public Task<PartialViewResult> Eliminar(int id)
		{
			throw new NotImplementedException();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public Task<PartialViewResult> Eliminar(int id, IFormCollection collection)
		{
			throw new NotImplementedException();
		}
	}
}

Web/PruebaTec.Gbso.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web/PruebaTec.Gbso.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaTec.Gbso.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
	
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PruebaTec.Gbso.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
						<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PruebaTec.Gbso.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/PruebaTec.Gbso.Web/Views/Usuario/Usuario.cshtml
@model PruebaTec.Gbso.Web.Models.UsuarioModel

<div>
    <h4>UsuarioModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoIdentificacionId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoIdentificacionId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasenia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contrasenia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Web/PruebaTec.Gbso.Web/Views/Usuario/Usuarios.cshtml
@model IEnumerable<PruebaTec.Gbso.Web.Models.UsuarioModel>

@{
    ViewData["Title"] = "Usuarios";
}

<h1>Usuarios</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoIdentificacionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contrasenia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoElectronico)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoIdentificacionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contrasenia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Web/PruebaTec.Gbso.Web/Views/Usuarios/Crear.cshtml
@model PruebaTec.Gbso.Web.Models.UsuarioModel
<h4>UsuarioModel</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Crear"
			  data-ajax="true"
			  data-ajax-method="POST"
			  data-ajax-update="#divEmp"
			  data-ajax-mode="replace">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Id" class="control-label"></label>
				<input asp-for="Id" class="form-control" />
				<span asp-validation-for="Id" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Nombre" class="control-label"></label>
				<input asp-for="Nombre" class="form-control" />
				<span asp-validation-for="Nombre" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Apellido" class="control-label"></label>
				<input asp-for="Apellido" class="form-control" />
				<span asp-validation-for="Apellido" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="TipoIdentificacionId" class="control-label"></label>
				<input asp-for="TipoIdentificacionId" class="form-control" />
				<span asp-validation-for="TipoIdentificacionId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Contrasenia" class="control-label"></label>
				<input asp-for="Contrasenia" class="form-control" />
				<span asp-validation-for="Contrasenia" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="CorreoElectronico" class="control-label"></label>
				<input asp-for="CorreoElectronico" class="form-control" />
				<span asp-validation-for="CorreoElectronico" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>
@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/PruebaTec.Gbso.Web/Views/Usuarios/Editar.cshtml
@model PruebaTec.Gbso.Web.Models.UsuarioModel

<h4>UsuarioModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoIdentificacionId" class="control-label"></label>
                <input asp-for="TipoIdentificacionId" class="form-control" />
                <span asp-validation-for="TipoIdentificacionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label"></label>
                <input asp-for="Contrasenia" class="form-control" />
                <span asp-validation-for="Contrasenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label"></label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/PruebaTec.Gbso.Web/Views/Usuarios/Index.cshtml
@model IEnumerable<PruebaTec.Gbso.Web.Models.UsuarioModel>

@{
    ViewData["Title"] = "Usuarios";
}
<partial></partial>
@Html.PartialAsync("Usuarios", Model);

Web/PruebaTec.Gbso.Web/Views/Usuarios/Usuario.cshtml
@model PruebaTec.Gbso.Web.Models.UsuarioModel

<div>
    <h4>UsuarioModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoIdentificacionId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoIdentificacionId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasenia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contrasenia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
    </dl>
</div>
<div>
    @*@Html.ActionLink("Editar", "Editar", Model }) |*@
    <a asp-action="Index">Back to List</a>
</div>

Web/PruebaTec.Gbso.Web/Views/Usuarios/Usuarios.cshtml
@model IEnumerable<PruebaTec.Gbso.Web.Models.UsuarioModel>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoIdentificacionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contrasenia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoElectronico)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoIdentificacionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contrasenia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", item) |
                @Html.ActionLink("Details", "Details", item) |
                @Html.ActionLink("Delete", "Delete", item)
            </td>
        </tr>
}
    </tbody>
</table>